### ISSUE TITLE
Credit where credit is due

### ISSUE THREAD

**Issue by fakhirali** [mohammadOsama141/user-driven-masking#1]
Umm this repo seems awfully similar to https://github.com/fakhirali/SAMuelable
The original repo deserves a mention in the README file at least.

**Comment by mohammadOsama141** [comment]
> Umm this repo seems awfully similar to https://github.com/fakhirali/SAMuelable The original repo deserves a mention in the README file at least.

Yes I am sorry I didnt know you invented masking
